import Head from 'next/head'
import { Box, Flex, Heading, SimpleGrid } from '@chakra-ui/react';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex >
          {/* Side Bar */}
          <SideBar />

          {/* Content Area */}
          <Box ml="250px" p={10} flex="1">
            <Box margin={10}>
              <Heading bgGradient='linear(to-tl, #6BA7FA, #274C86)' bgClip='text' fontSize={50} mb={10}>
                Start Page
              </Heading>
              <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} spacing={10}>
              </SimpleGrid>
            </Box>

          </Box>
        </Flex>
      </main>
    </>
  )
}
